include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print

analyzer:
  errors:
    prefer_const_constructors: warning
  exclude:
    - build/**
    - ios/**
    - macos/**
    - web/**
